//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MushhoodEntities : DbContext
    {
        public MushhoodEntities()
            : base("name=MushhoodEntities")
        {
            
                Configuration.ProxyCreationEnabled = false;
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alpha> alphas { get; set; }
        public virtual DbSet<beta> betas { get; set; }
    }
}
